### ISSUE TITLE
JavaScript error on run

### ISSUE THREAD

**Issue by PrismaWeaver** [nateshmbhat/windows-terminal-tweaker#5]
error reads:

Uncaught Exception:
TypeError: Cannot read property 'toString' of undefined
    at ReadFileContext.callback (...\wind-unpacked\resources\app.asar\build\electron.js:47:47)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs:js:247:13)

results in Terminal Tweaker running successfully, but there are no available options under each tab.

**Comment by KrunchMuffin** [comment]
confirmed

**Comment by creizlein** [comment]
Confirmed x2, same here.

**Comment by dominic-ks** [comment]
Also confirmed, no idea on a workaround.

**Comment by umernalla** [comment]
Same here
Uncaught Exception:
TypeError: Cannot read property 'toString' of undefined
    at ReadFileContext.callback (C:\Downloads\Terminal.Tweaker.Portable\win-unpacked\resources\app.asar\build\electron.js:47:47)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:247:13)

**Comment by jhilker98** [comment]
Confirmed here as well.

**Comment by nateshmbhat** [comment]
mostly the issue here is that microsoft have changed the location to their terminal configuration file and that's why its not able to find that file in the location which was there before. 

i am having issues in booting up my windows machine currently. so it will take some time to set all this up. i plan to do it when i get some time. 

Meanwhile , if anyone wants to open a PR, that would be very helpful. It will be a small change i think in this particular function : 

https://github.com/nateshmbhat/windows-terminal-tweaker/blob/6df689a8579c1d094c2e7c58fb7fff2a28e5ad04/main/src/electron.ts#L33

**Comment by enxg** [comment]
> mostly the issue here is that microsoft have changed the location to their terminal configuration file and that's why its not able to find that file in the location which was there before.
> 
> i am having issues in booting up my windows machine currently. so it will take some time to set all this up. i plan to do it when i get some time.
> 
> Meanwhile , if anyone wants to open a PR, that would be very helpful. It will be a small change i think in this particular function :
> 
> https://github.com/nateshmbhat/windows-terminal-tweaker/blob/6df689a8579c1d094c2e7c58fb7fff2a28e5ad04/main/src/electron.ts#L33

I ran the code on my machine and it found a match, path seems correct, I think you only need to publish a new release.

**Comment by nateshmbhat** [comment]
Unfortunately Microsoft has changed the format of the file now in latest versions.

I will have to do quite some changes to this to work. I will see if I can tweak this up some places to fix it.

**Comment by andyrz** [comment]
Any plans on resolving this issue? The tool is essentially useless....

**Comment by binbard** [comment]
Not yet fixed, still reproduced that error, on windows 11.
![2022-01-16 17_35_56-Error](https://user-images.githubusercontent.com/28684962/149659932-3af0955c-aa84-4cc2-8d05-48a0a3ae750e.png)

**Comment by manusoftar** [comment]
Bump
